name: Express API CI/CD

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: cicd
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-timeout=5s
          --health-interval=5s
          --health-retries=5
    
    env:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/cicd
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Run clean install
        run: npm ci
      - name: Generate prisma client
        run: npx prisma generate
      - name: Migrate prisma in deployment
        run: npx prisma migrate deploy
      - name: Run tests
        run: npm run test
  
  docker:
    needs: ci
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    
    env:
      OWNER: alanchristopher
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Login to github registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build docker image
        run: docker build -t ghcr.io/${{ env.OWNER }}/express-api:latest .
      - name: Push the built image
        run: docker push ghcr.io/${{ env.OWNER }}/express-api:latest
    
  deploy:
    needs: docker
    runs-on: ubuntu-latest

    env:
      OWNER: alanchristopher
    
    steps:
      - name: Simulate deployment
        run: echo "pulling image..." docker pull ghcr.io/${{ env.OWNER }}/express-api:latest
      - name: Run the container
        run: docker run -d -p "3000:3000" ghcr.io/${{ env.OWNER }}/express-api:latest echo "App deployed"