name: Express API CI/CD

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: cicd
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5
    
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/cicd
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npx prisma generate
      - run: npx prisma migrate deploy
      - run: npm run test
  
  docker:
    needs: ci
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Login to github registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build docker image
        run: docker build -t ghcr.io/${{ github.repository }}/express-api:latest .
      - name: Push image
        run: docker push ghcr.io/${{ github.repository }}/express-api:latest
    
  deploy:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Stimulate deployment
        run:
          echo "Pulling image..."
          docker pull ghcr.io/${{ github.repository }}/express-api:latest
          echo "Running container..."
          docker run -d -p "3000:3000" ghcr.io/${{ github.repository }}/express-api:latest
          echo "App deployed..."    
